apiVersion: v1
kind: Service
metadata:
  name: neovaclean-app-service
spec:
  selector:
    app: neovaclean-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Your Node.js app runs on port 3000
  type: LoadBalancer

